vich_uploader:
    db_driver: orm

    mappings:
        post_file:
            uri_prefix: uploads/posts
            upload_destination: '%post_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
